name: scjn-transcripts
services:
    db:
        image: mongo:latest
        env_file:
            - mongo/.env
        ports:
            - "27017:27017"
        volumes:
            - ./docker/mongo/data:/data/db
            - ./docker/mongo/scripts/init.js:/docker-entrypoint-initdb.d/init.js:ro
        networks:
            - lex-network
    cache:
        image: redis:latest
        ports:
            - "6379:6379"
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
          - ./docker/redis/data:/data
          - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
        networks:
            - lex-network

networks:
    lex-network:
        driver: bridge